//ENTRY(ID,  var,                            unit,  name,                   minvalue,    maxvalue  )

ENTRY('1', sensorData.voltage,                "V",  "battery voltage",           0.0,        25.0  )
ENTRY('2', sensorData.wheelVel[0],             "",  "vel 1",                   -50.0,        50.0  )
ENTRY('3', sensorData.wheelVel[1],             "",  "vel 2",                   -50.0,        50.0  )
ENTRY('4', sensorData.wheelVel[2],             "",  "vel 3",                   -50.0,        50.0  )
ENTRY('5', sensorData.iBus[0],                "A",  "iBus 1",                   -1.0,         9.0  )
ENTRY('6', sensorData.iBus[1],                "A",  "iBus 2",                   -1.0,         9.0  )
ENTRY('7', sensorData.iBus[2],                "A",  "iBus 3",                   -1.0,         9.0  )
ENTRY('a', input.a,                            "",  "input a",                -127.0,       127.0  )
ENTRY('s', input.b,                            "",  "input b",                -127.0,       127.0  )
ENTRY('d', input.c,                            "",  "input c",                -127.0,       127.0  )
ENTRY('f', input.d,                            "",  "input d",                -127.0,       127.0  )
ENTRY('g', sensorData.taskTime[ttmin],       "us",  "2ms task min time",         0.0,      2500.0  )
ENTRY('h', sensorData.taskTime[ttmax],       "us",  "2ms task max time",         0.0,      2500.0  )
ENTRY('j', sensorData.taskTime[ttavg],       "us",  "2ms task avg time",         0.0,      2500.0  )
ENTRY('V', actuator.torque[0],                "A",  "motor 1 current",         -40.0,        40.0  )
ENTRY('B', actuator.torque[1],                "A",  "motor 2 current",         -40.0,        40.0  )
ENTRY('N', actuator.torque[2],                "A",  "motor 3 current",         -40.0,        40.0  )
ENTRY('8', sensorData.pitchAngleAcc,        "deg",  "pitch acc",               -20.0,        20.0  )
ENTRY('9', sensorData.rollAngleAcc,         "deg",  "roll acc",                 -5.0,         5.0  )
ENTRY('0', sensorData.pitchAngle,           "deg",  "pitch",                   -20.0,        20.0  )
ENTRY('l', sensorData.rollAngle,            "deg",  "roll",                     -5.0,         5.0  )
ENTRY('A', controlState.targetPitchI,       "deg",  "target pitch i" ,         -20.0,        20.0  )
ENTRY('S', controlState.targetPitch + controlPara.pitchWP, "deg", "target pitch", -20.0,     20.0  )
ENTRY('D', controlState.targetRollI,        "deg",  "target roll i",           -5.0,          5.0  )
ENTRY('F', controlState.targetRoll + controlPara.rollWP, "deg", "target roll", -5.0,          5.0  )
ENTRY('q', sensorData.acc.x,                  "g",  "acc x",                    -1.0,         1.0  )
ENTRY('w', sensorData.acc.y,                  "g",  "acc y",                    -1.0,         1.0  )
ENTRY('e', sensorData.acc.z,                  "g",  "acc z",                    -1.0,         1.0  )
ENTRY('r', sensorData.gyro.x,             "deg/s",  "gyro x",                 -250.0,       250.0  )
ENTRY('t', sensorData.gyro.y,             "deg/s",  "gyro y",                 -250.0,       250.0  )
ENTRY('z', sensorData.gyro.z,             "deg/s",  "gyro z",                 -250.0,       250.0  )
ENTRY('u', sensorData.magnet.x,              "µT",  "magnet x",               -100.0,       100.0  )
ENTRY('i', sensorData.magnet.y,              "µT",  "magnet y",               -100.0,       100.0  )
ENTRY('o', sensorData.magnet.z,              "µT",  "magnet z",               -100.0,       100.0  )
ENTRY('y', joystickReport.x,                   "", "joystick x",                 0.0,       255.0  )
ENTRY('x', joystickReport.y,                   "", "joystick y",                 0.0,       255.0  )
ENTRY('c', joystickReport.z,                   "", "joystick z",                 0.0,       255.0  )
ENTRY('v', joystickReport.rz,                  "", "joystick rz",                0.0,       255.0  )
ENTRY('b', joystickReport.buttons,             "", "joystick buttons",           0.0,      4096.0  )
ENTRY('n', joystickReport.hat,                 "", "joystick hat",               0.0,       255.0  )
ENTRY('m', joystickTimeout,                    "", "joystick timeout",           0.0,       100.0  )


ENTRY(0,   actuator.disabled,                 "-",  "end of table",              0.0,         0.0  )
