//ENTRY(ID, var,                     increment,    unit,    name                              )

ENTRY('1',  controlPara.pPartSpeedPitch, 0.01,       "",    "p part speed pitch"              )
ENTRY('2',  controlPara.iPartSpeedPitch, 0.01,       "",    "i part speed pitch"              )
ENTRY('3',  controlPara.pPartPitch,      0.01,       "",    "p part pitch"                    )
ENTRY('4',  controlPara.dPartPitch,      0.01,       "",    "d part pitch"                    )
ENTRY('5',  controlPara.pitchWP,         0.01,       "",    "pitch wp"                        )
ENTRY('6',  controlPara.speedPitchFilter, 1.0,     "ms",    "speed pitch filter"                    )
ENTRY('7',  controlPara.pPartSpeedRoll,  0.01,       "",    "p part speed roll"               )
ENTRY('8',  controlPara.iPartSpeedRoll,  0.01,       "",    "i part speed roll"               )
ENTRY('9',  controlPara.pPartRoll,       0.01,       "",    "p part roll"                     )
ENTRY('0',  controlPara.dPartRoll,       0.01,       "",    "d part roll"                     )
ENTRY('q',  controlPara.rollWP,          0.01,       "",    "roll wp"                         )
ENTRY('w',  controlPara.speedRollFilter,  1.0,     "ms",    "speed roll filter"               )
ENTRY('e',  controlPara.dPartYaw,        0.01,       "",    "d part yaw"                      )
ENTRY('r',  controlPara.gyroOffset.x,    0.01,  "deg/s",    "gyro offset x"                   )
ENTRY('t',  controlPara.gyroOffset.y,    0.01,  "deg/s",    "gyro offset y"                   )
ENTRY('z',  controlPara.gyroOffset.z,    0.01,  "deg/s",    "gyro offset z"                   )
ENTRY('u',  controlPara.gyroFilter.x,     1.0,     "ms",    "gyro filter x"                   )
ENTRY('i',  controlPara.gyroFilter.y,     1.0,     "ms",    "gyro filter y"                   )
ENTRY('o',  controlPara.gyroFilter.z,     1.0,     "ms",    "gyro filter z"                   )
ENTRY('a',  controlPara.curveRoll,       0.01,       "",    "curve roll"                      )

ENTRY(  0,  controlPara.dPartPitch,      0.01,       "",    "end of table"                    )
